# Generated by Django 5.2.5 on 2025-08-06 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_add_unique_user_pair_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='user1_not_equal_user2',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
